create table info_exec_path (info_hibid bytea not null, name varchar(255), errorCode integer, errorCodeAsString varchar(255), errorDetails varchar(255), errorMessage varchar(255), errorString varchar(255), retryable boolean not null, pendWorkBasket varchar(255), prevPendWorkBasket varchar(255), status varchar(255), step varchar(255), stepResponseType varchar(255), tbcSlaWorkBasket varchar(255), ticket varchar(255), exec_path_key varchar(255) not null, primary key (info_hibid, exec_path_key));
create table info_variables (info_hibid bytea not null, variablesMap_hibid bytea not null, variable_key varchar(255) not null, primary key (info_hibid, variable_key));
create table milestone (hibid bytea not null, action varchar(255), appliedAtAge varchar(255), appliedAtTimestamp timestamp(6), clockStarts smallint, followBusinessCalendar boolean, name varchar(255), setupOn smallint, type smallint, userData varchar(255), workBasketName varchar(255), primary key (hibid));
create table milestone_next_milestone (Milestone_hibid bytea not null, furtherMilestones_hibid bytea not null);
create table next_milestone (hibid bytea not null, appliedAtAge varchar(255), appliedAtTimestamp timestamp(6), offset numeric(21,0), repeat integer, primary key (hibid));
create table route_branch (hibid bigserial not null, name varchar(255), next varchar(255), primary key (hibid));
create table route_branches (route_id bigint not null, branches_hibid bigint not null, branch_key varchar(255) not null, primary key (route_id, branch_key));
create table step (step_class varchar(31) not null, hibid bigserial not null, name varchar(255) not null, type varchar(255) not null, next_step varchar(255), component_name varchar(255), user_data varchar(255), componant_name varchar(255), primary key (hibid));
create table ticket (hibid bigserial not null, name varchar(255), step varchar(255), primary key (hibid));
create table workflow_definition (hibid bytea not null, name varchar(255) not null, primary key (hibid));
create table workflow_steps (workflow_hibid bytea not null, steps_hibid bigint not null, step_key varchar(255) not null, primary key (workflow_hibid, step_key));
create table workflow_tickets (workflow_hibid bytea not null, tickets_hibid bigint not null, ticket_key varchar(255) not null, primary key (workflow_hibid, ticket_key));
create table workflow_variable (hibid bytea not null, comment varchar(255), name varchar(255), type varchar(255), value varchar(255), workflow_id bytea, primary key (hibid));
create table WorkflowInfo (hibid bytea not null, caseId varchar(255), isComplete boolean, isPendAtSameStep boolean, lastUnitExecuted bytea, pendExecPath varchar(255), ticket varchar(255), ticketUrt smallint, workflowDefinition_hibid bytea, primary key (hibid));
alter table if exists info_variables add constraint UK_psklufddjpy9lci28bkx00dym unique (variablesMap_hibid);
alter table if exists milestone_next_milestone add constraint UK_5pg1q76nflqqo4ih3savqtf6p unique (furtherMilestones_hibid);
alter table if exists route_branches add constraint UK_etsv5x3jejtw7k9yu7uyk0iu unique (branches_hibid);
alter table if exists workflow_steps add constraint UK_5pky3nvqexrt3kf6kbma7dixv unique (steps_hibid);
alter table if exists workflow_tickets add constraint UK_9sm0ygag3qsoibrgi67yy5c2e unique (tickets_hibid);
alter table if exists info_exec_path add constraint FKsf40dgjd5srtxm5d5acvwm3jg foreign key (info_hibid) references WorkflowInfo;
alter table if exists info_variables add constraint FKrd7e4dm9m1kxjjeittj85r4od foreign key (variablesMap_hibid) references workflow_variable;
alter table if exists info_variables add constraint FK3eimgpi41pj0ykbdkj7gg0h9g foreign key (info_hibid) references WorkflowInfo;
alter table if exists milestone_next_milestone add constraint FKgwgsuntog94qxd3nyw4ht6ayc foreign key (furtherMilestones_hibid) references next_milestone;
alter table if exists milestone_next_milestone add constraint FKrxragktfmfisx3fxyt1yd6nxh foreign key (Milestone_hibid) references milestone;
alter table if exists route_branches add constraint FKo5boq3lhaqasjk57fj9qm13va foreign key (branches_hibid) references route_branch;
alter table if exists route_branches add constraint FKlegwkb9nj75xf5lgv3h3fx4v3 foreign key (route_id) references step;
alter table if exists workflow_steps add constraint FKfl7kwh57n4994wevvi7prl2k0 foreign key (steps_hibid) references step;
alter table if exists workflow_steps add constraint FKe1qbli2n5omd4v0tfmn7o38lr foreign key (workflow_hibid) references workflow_definition;
alter table if exists workflow_tickets add constraint FKrb7i5xsd4ikrqinnjpgkoaxx2 foreign key (tickets_hibid) references ticket;
alter table if exists workflow_tickets add constraint FKc03n1ki33fc23revrp5te510k foreign key (workflow_hibid) references workflow_definition;
alter table if exists workflow_variable add constraint FKqlhtfop8yhdjxseahscrbi593 foreign key (workflow_id) references workflow_definition;
alter table if exists WorkflowInfo add constraint FK3isogn3fd78lu9e53mn7mi3xd foreign key (workflowDefinition_hibid) references workflow_definition;
